src/Entity/Tva.php
<?php

namespace App\Entity;

use App\Repository\TvaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TvaRepository::class)]
class Tva
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $Statut = null;

    #[ORM\Column]
    private ?float $valeur = null;

    #[ORM\OneToMany(mappedBy: 'Tva', targetEntity: CommandeAchat::class)]
    private Collection $commandeAchats;

    public function __construct()
    {
        $this->commandeAchats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isStatut(): ?bool
    {
        return $this->Statut;
    }

    public function setStatut(bool $Statut): static
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getValeur(): ?float
    {
        return $this->valeur;
    }

    public function setValeur(float $valeur): static
    {
        $this->valeur = $valeur;

        return $this;
    }

    /**
     * @return Collection<int, CommandeAchat>
     */
    public function getCommandeAchats(): Collection
    {
        return $this->commandeAchats;
    }

    public function addCommandeAchat(CommandeAchat $commandeAchat): static
    {
        if (!$this->commandeAchats->contains($commandeAchat)) {
            $this->commandeAchats->add($commandeAchat);
            $commandeAchat->setTva($this);
        }

        return $this;
    }

    public function removeCommandeAchat(CommandeAchat $commandeAchat): static
    {
        if ($this->commandeAchats->removeElement($commandeAchat)) {
            // set the owning side to null (unless already changed)
            if ($commandeAchat->getTva() === $this) {
                $commandeAchat->setTva(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->valeur;
        
    }
}

src/Form/TvaType.php
<?php

namespace App\Form;

use App\Entity\Tva;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TvaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Statut', ChoiceType::class,[
                'choices' => [
                    'Actif' => true,
                    'Inactif' => false,
                ],
                'placeholder' => 'Choisissez une option',
                'required'=> true,
            ]
            
            )
            ->add('valeur',NumberType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tva::class,
        ]);
    }
}

src/Controller/TvaController.php
<?php

namespace App\Controller;

use App\Entity\Tva;
use App\Form\TvaType;
use App\Repository\TvaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/Tva')]
class TvaController extends AbstractController
{
    #[Route('/read', name: 'liste_tva',methods: ['GET'])]
    public function index(TvaRepository $tvaRepository): Response
    {
        $tva= $tvaRepository->findAll();
        return $this->render('tva/listeTva.html.twig', [
            'tvas' => $tva,
        ]);
    }
    #[Route('/create', name: 'create_tva',methods: ['GET', 'POST'])]
    public function create(TvaRepository $tvaRepository, Request $request): Response
    {
        $tva=new Tva();
        $formulaire=$this->createForm(TvaType::class, $tva);
        $formulaire->handleRequest($request);
        if ($formulaire->isSubmitted() && $formulaire->isValid()) {
            $tvaRepository->save($tva, true);
            $this->addFlash(
                'notice',
                'nouvelle Tva créée avec succès !'
            );
            return $this->redirectToRoute('create_tva');
        }
        return $this->render('tva/AjouterTva.html.twig', [
            'formulaire' => $formulaire->createView(),
        ]);
    }
    #[Route('/update/{id}', name: 'update_tva',methods: ['GET', 'POST'])]
    public function update(TvaRepository $tvaRepository, Tva $tva, Request $request): Response
    {
        $formulaire=$this->createForm(TvaType::class, $tva);
        $formulaire->handleRequest($request);
        if ($formulaire->isSubmitted() && $formulaire->isValid()) {
            $tvaRepository->save($tva, true);
            $this->addFlash(
                'notice',
                ' Tva modifiée avec succès !'
            );
            return $this->redirectToRoute('liste_tva');
        }
        return $this->render('tva/ModifierTva.html.twig', [
            'formulaire' => $formulaire->createView(),
        ]);
    }
    #[Route('/delete/{id}', name: 'delete_tva')]
    public function delete(Tva $Tva, Request $request, TvaRepository $TvaRepository): Response
    {
        
        $TvaRepository->remove($Tva, true);
        $this->addFlash(
            'notice',
            ' Tva supprimée avec succès !'
        );
       

        return $this->redirectToRoute('liste_tva');
    }
}

templates/tva/AjouterTva.html.twig
{% extends "main/template.html.twig" %}

{% block contenu %}
<div class="row">
    <div class="col-sm-12">
        {% for message in app.flashes('notice') %}
            <div class="alert alert-success" role="alert">
                <div class="iq-alert-text">
                    {{message}}
                </div>
             </div>  
            {% endfor %}
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <div class="header-title">
                    <h4 class="card-title">Ajouter Une Tva</h4>
                </div>
            </div>
            <div class="card-body">
                {{form_start (formulaire)}}
               
                    <div class="row">

                        <div class="col-md-6">   

                            <div class="form-group">
                                {{ form_label (formulaire.valeur,"Valeur (%)*")}}
                                {{form_widget(formulaire.valeur, {'attr':{class:'form-control',"placeholder":"Entrer la valeur de la tva"}})}} 
                                <div class="help-block with-errors"></div>
                            </div>

                        </div>    
                        <div class="col-md-6">
                            <div class="form-group">
                                {{form_label(formulaire.Statut,"Statut *")}}
                                {{form_widget(formulaire.Statut, {'attr':{class:'selectpicker form-control', "data-style":"py-0"}})}}
                            </div>
                        </div>

                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Ajouter</button>
                    <a href="{{ path('liste_tva') }}"class="btn btn-success mr-2">Liste</a>
               
                {{form_end (formulaire)}}
            </div>
        </div>
    </div>
</div>
{% endblock contenu %}

templates/tva/ListeTva.html.twig
{% extends "main/template.html.twig" %}
{% block contenu %}
<div class="row">
    <div class="col-lg-12">
        {% for message in app.flashes('notice') %}
        <div class="alert alert-warning" role="alert">
            <div class="iq-alert-text">
                {{message}}
            </div>
         </div>  
        {% endfor %}
        <div class="d-flex flex-wrap align-items-center justify-content-between mb-4">
            <div>
                <h4 class="mb-3">Liste Des Tva</h4>
              
            </div>
            <a href="{{path ('create_tva')}}" class="btn btn-primary add-list"><i class="ri-add-line" style="color: #ffffff;"></i>Ajouter</a>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="table-responsive rounded mb-3">
        <table class="data-table table mb-0 tbl-server-info">
            <thead class="bg-white text-uppercase">
                <tr class="ligth ligth-data">
                   
                    <th>Valeur(%)</th>
                    <th>Statut</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody class="ligth-body">
                {% for tva in tvas %}
                    
                <tr>
                    
                    <td>{{tva.valeur}}</td>
                    <td>{% if tva.statut == 1 %}
                        <div class="badge badge-success">Actif</div>
                        {% else %}
                        <div class="badge badge-warning">Inactif</div>
                    {% endif %}</td>
                    <td>
                        <div class="d-flex align-items-center list-action">
                            
                            <a class="badge bg-success mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Modifier"
                                href="{{path ('update_tva', {'id': tva.id})}}"><i class="ri-pencil-line mr-0"></i></a>
                            <a class="badge bg-warning mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="supprimer"
                                href="{{path ('delete_tva', {'id': tva.id})}}"><i class="ri-delete-bin-line mr-0"></i></a>
                            
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenu %}

templates/tva/ModifierTva.html.twig
{% extends "main/template.html.twig" %}

{% block contenu %}
<div class="row">
    <div class="col-sm-12">
        {% for message in app.flashes('notice') %}
            <div class="alert alert-success" role="alert">
                <div class="iq-alert-text">
                    {{message}}
                </div>
             </div>  
            {% endfor %}
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <div class="header-title">
                    <h4 class="card-title">Modifier la  Tva</h4>
                </div>
            </div>
            <div class="card-body">
                {{form_start (formulaire)}}
               
                    <div class="row">

                        <div class="col-md-6">   

                            <div class="form-group">
                                {{ form_label (formulaire.valeur,"Valeur *")}}
                                {{form_widget(formulaire.valeur, {'attr':{class:'form-control',"placeholder":"Entrer la valeur de la tva"}})}} 
                                <div class="help-block with-errors"></div>
                            </div>

                        </div>    
                        <div class="col-md-6">
                            <div class="form-group">
                                {{form_label(formulaire.Statut,"Statut *")}}
                                {{form_widget(formulaire.Statut, {'attr':{class:'selectpicker form-control', "data-style":"py-0"}})}}
                            </div>
                        </div>

                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Modifier</button>
                    <a href="{{ path('liste_tva') }}"class="btn btn-success mr-2">Liste</a>
               
                {{form_end (formulaire)}}
            </div>
        </div>
    </div>
</div>
{% endblock contenu %}

templates/tva/_delete_form.html.twig
<form method="post" action="{{ path('delete_tva', {'id': tva.id}) }}" onsubmit="return confirm('Etes Vous sûr de supprimer cet élément ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tva.id) }}">
    <button class="btn btn-warning mt-2">Supprimer</button>
</form>